create :: user CRUD
mash-up-kr/node-11th-toy-hellTaBus pull request #2
Opened 2021-08-22 15:29 UTC by nari1021

사용자 부분 CRUD 입니다.

2021-08-23 01:39 UTC, ujusy requested changes
고생하셨습니다!!!😳👍

2021-08-23 01:39 UTC, ujusy commented on src/modules/user/user.service.ts
> +    user.birthday = createUserDto.birthday;
createUser DTO 파일이 존재해서 중복되는 것 같은데 respository만 inject하는게 어떨까요?
+ 기존 유저 존재하는 지에 대한 로직 처리도 있으면 좋을 것 같습니다.
```suggestion
  createUser(createUserDto: CreateUserDto) {
    const userData = await this.userRepository.save({
        email: createUserDto.email,
        name: createUserDto.name,
        ....작성
        password: createUserDto.password,
      });
  
      delete userData.password;
  
      return userData;
  }
```

2021-08-23 01:39 UTC, ujusy commented on src/modules/user/user.service.ts
> +    return getRepository(User).save(user);
```suggestion
@InjectRepository(User) private userRepository: Repository<User>,
```
위와 같은 형태루요!

2021-08-23 01:39 UTC, ujusy commented on src/modules/user/dto/create-user.dto.ts
> +
dto에 작성된 것이 swagger로 보여지므로 조금 더 자세하게 작성해주셔도 좋을 것 같습니다!

2021-08-23 01:39 UTC, ujusy commented on src/modules/user/dto/create-user.dto.ts
> +  @ApiProperty({description: '사용자 아이디'})
```suggestion
  @ApiProperty({example: 'ujusy', description: '사용자 아이디'})
```

2021-08-23 01:39 UTC, ujusy commented on src/modules/user/dto/create-user.dto.ts
> +  @ApiProperty({description: '사용자 email'})
```suggestion
  @IsEmail()
  @ApiProperty({description: '사용자 email'})
```

2021-08-23 01:39 UTC, ujusy commented on src/modules/user/dto/create-user.dto.ts
> +  password: string;
```suggestion
  @IsString()
  @IsNotEmpty()
  @ApiProperty({example: '1234',description: '사용자 비밀번호'})
  password: string;
```

2021-08-24 10:50 UTC, pengin7384 approved these changes
LGTM!

2021-08-24 11:16 UTC, haron47 approved these changes
LGTM👍

2021-08-29 15:12 UTC, merged