Feature/login
mash-up-kr/node-11th-toy-hellTaBus pull request #3
Opened 2021-09-02 18:08 UTC by ujusy

2021-09-02 19:01 UTC, pengin7384 requested changes
코멘트 남겼습니다! 확인 부탁드립니다 🙃

2021-09-02 19:01 UTC, pengin7384 commented on src/auth/jwt.strategy.ts
> +      userEmail: payload.email,
```suggestion
      user: {
        id: ~~,
        email: ~~,
      }
```
어떠신가요?

2021-09-02 19:01 UTC, pengin7384 commented on src/app.controller.ts
> +    @Get()
Indentation?

2021-09-02 19:01 UTC, pengin7384 commented on src/auth/auth.module.ts
> +      secret: jwtConstants.secret,
```suggestion
      secret: JwtConstants.SECRET,
```
nest.js docs에는 `jwtConstants.secret`이 맞지만 저희가 쓰기로한 Google style guide에서는 다음과 같이 쓰는게 맞는 네이밍 컨벤션 같습니다!
ref: https://google.github.io/styleguide/jsguide.html#naming-constant-names

2021-09-02 19:01 UTC, pengin7384 commented on src/auth/auth.service.ts
> +    const password = await bcrypt.compare(pass, user.password);
```suggestion
    const isSamePassword = await bcrypt.compare(pass, user.password);
```
다음과 같이 boolean임을 알 수 있으면 좋을 거 같습니다 🙃

2021-09-02 19:01 UTC, pengin7384 commented on src/auth/auth.service.ts
> +    });
`userRepository` 말고 `userService`를 주입받고 `findUserByEmail(email: string)`를 사용하면 어떨까요? 
ref: https://docs.nestjs.com/security/authentication#jwt-functionality -> `auth/auth.service.ts`

2021-09-02 19:01 UTC, pengin7384 commented on src/auth/constant.ts
> +  secret: 'helltabus',
Private하게 관리되어야하지 않을까요!?

2021-09-02 19:01 UTC, pengin7384 commented on src/error.ts
> +};
👍

2021-09-02 19:01 UTC, pengin7384 commented on src/main.ts
> +  console.log('server listening on 3000');
포트를 외부에서 변경할 수 있으면 좋을 거 같습니다. .env??

2021-09-02 19:01 UTC, pengin7384 commented on src/migrations/1630589061298-generate.ts
> +}
👍

2021-09-02 19:01 UTC, pengin7384 commented on src/profile/entities/profile.entity.ts
> +  updatedAt: Date;
TypeORM에서 지원하는 `@CreateDateColumn` & `@UpdateDateColumn`를 사용해보면 어떨까요?
ref: https://typeorm.io/#/entities/special-columns

2021-09-02 19:01 UTC, pengin7384 commented on src/user/dto/createUserDto.ts
>    @ApiProperty({example: '펭귄', description: '사용자 닉네임'})
🐧

2021-09-02 19:01 UTC, pengin7384 commented on src/user/entities/user.entity.ts
> +  deletedAt: Date | null;
ditto. `@DeleteDateColumn`?

2021-09-02 19:01 UTC, pengin7384 commented on src/user/user.service.ts
> +    if (user) throw new BadRequestException(Err.EXISTING_USER);
👍

2021-09-02 19:01 UTC, pengin7384 commented on src/user/user.service.ts
> +    const password = await bcrypt.hash(createUserDto.password, 12);
평문 비밀번호와 해쉬된 비밀번호를 구분하기위해 `hashedPassword`는 어떨까요?

2021-09-02 19:01 UTC, pengin7384 commented on src/user/user.service.ts
>      const userData = await this.userRepository.save({
```suggestion
    const createdUser = await this.userRepository.save({
```
`createdUser`로 변경하면 어떨까요?

2021-09-02 19:07 UTC, pengin7384 commented on src/user/user.service.ts
> +    const password = await bcrypt.hash(createUserDto.password, 12);
or `passwordHash`

2021-09-02 19:08 UTC, pengin7384 commented on src/user/user.service.ts
> +    const password = await bcrypt.hash(createUserDto.password, 12);
`passwordHash`가 직관적인 거 같습니다

2021-09-03 12:59 UTC, minidonut commented on src/user/dto/createUserDto.ts
>    @ApiProperty({example: '펭귄', description: '사용자 닉네임'})
🐿️

2021-09-03 13:00 UTC, minidonut commented on src/user/user.controller.ts
> +    private authService: AuthService,
여긴 왜 readonly를 안하셨나여

2021-09-03 13:11 UTC, ujusy commented on src/user/user.controller.ts
> +    private authService: AuthService,
앗...실수..인 것 같습니다..리뷰감사합니다 세훈님👍😎😎😎

2021-09-03 13:17 UTC, ujusy commented on src/auth/constant.ts
> +  secret: 'helltabus',
나중에 클라우드 사용할 때 환경변수로 빼는게 어떨까요오?

2021-09-03 13:17 UTC, ujusy commented on src/profile/entities/profile.entity.ts
> +  updatedAt: Date;
좋은것 같아요

2021-09-03 13:33 UTC, haron47 requested changes

2021-09-03 13:33 UTC, haron47 commented on src/main.ts
> +
```suggestion
app.useGlobalPipes(new ValidationPipe());

```
npm i --save class-transformer

2021-09-03 13:36 UTC, haron47 commented on src/error.ts
> +};
👍👍

2021-09-03 15:18 UTC, haron47 commented on src/main.ts
> +
```suggestion
app.useGlobalFilters(new HttpExceptionFilter());
```

2021-09-03 15:18 UTC, haron47 commented on src/main.ts
> +
HttpExceptionFilter() 이용하면 동일한 error response 줄 수 있을 것 같습니당!

httpException.filter.ts
```
import { ExceptionFilter, Catch, ArgumentsHost, HttpException } from '@nestjs/common';
import { Response } from 'express';

@Catch(HttpException)
export class HttpExceptionFilter implements ExceptionFilter {
    catch(exception: HttpException, host: ArgumentsHost) {
        const ctx = host.switchToHttp();
        const response = ctx.getResponse<Response>();
        const status = exception.getStatus();
        const err = exception.getResponse() as
            | { message: any; code: number }
            | { error: string; message: string[]; code: number | null };
        if (err.code) {
            return response.status(status).json({
                success: false,
                code: err.code,
                data: err.message,
            });
        }
        response.status(status).json({ success: false, code: status, data: err.message });
    }
}
```

2021-09-03 15:33 UTC, haron47 commented on .gitignore
> +
```suggestion
fd
```

2021-09-04 05:50 UTC, nari1021 approved these changes
LGTM👍🏻

2021-09-04 14:13 UTC, ujusy commented on src/auth/auth.service.ts
> +    });
현재 `userService`에 `findOne`처럼 `eamil`을 가지고 찾는 API 가 없으므로 `pass`해도 될까요? 추후에 `user` 리팩토링할 때 추가해도 될것같습니다!

2021-09-06 13:54 UTC, ujusy commented on src/user/user.service.ts
> +    const password = await bcrypt.hash(createUserDto.password, 12);
`hashedPassword`로 교체하겠습니다

2021-09-06 14:21 UTC, ujusy commented
리뷰 반영하여 다시 올렸습니다! 반영이 안된부분 몇 가지는 코멘트 했으니 참고 부탁드립니다!!✌️

2021-09-06 18:01 UTC, haron47 commented
LGTM👍

2021-09-06 18:03 UTC, haron47 approved these changes
LGTM👍

2021-09-07 13:32 UTC, pengin7384 commented on src/auth/auth.service.ts
> +    });
👍

2021-09-07 13:33 UTC, pengin7384 commented on src/user/user.service.ts
> +    const password = await bcrypt.hash(createUserDto.password, 12);
👍

2021-09-07 13:46 UTC, pengin7384 commented on src/auth/constant.ts
> +  secret: 'helltabus',
좋습니다아

2021-09-07 13:47 UTC, pengin7384 approved these changes
![image](https://user-images.githubusercontent.com/32831939/132355761-4d54c5ee-ba70-4eaf-a88c-de2a04006950.png)
LGTM! 반영 감사합니다 🙃

2021-09-07 13:48 UTC, merged